name: Setup cloudflared
description: Setup/Install Cloudflare Tunnel client for GitHub Actions
branding:
  icon: cloud
  color: orange
inputs:
  cloudflare_tunnel_service_token_id:
    description: Cloudflare Tunnel service token ID
    required: true
  cloudflare_tunnel_service_token_secret:
    description: Cloudflare Tunnel service token secret
    required: true
  cloudflare_tunnel_hostname:
    description: Cloudflare Tunnel hostname
    required: true
  cloudflare_tunnel_listen:
    description: Cloudflare Tunnel listen address
    required: false
    default: "127.0.0.1:1234"
  autostart:
    description: Autostart Cloudflare Tunnel in the background
    required: false
    default: true
    
runs:
  using: composite
  steps:
    - name: Download cloudflared for Linux
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download/Linux.sh
      
    - name: Install cloudflared on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: cloudflared
      
    - name: Start Cloudflare Tunnel in the background
      if: inputs.autostart != 'false'
      shell: bash
      env:
        TUNNEL_SERVICE_TOKEN_ID: ${{ inputs.cloudflare_tunnel_service_token_id }}
        TUNNEL_SERVICE_TOKEN_SECRET: ${{ inputs.cloudflare_tunnel_service_token_secret }}
        cloudflare_tunnel_hostname: ${{ inputs.cloudflare_tunnel_hostname }}
        cloudflare_tunnel_listen: ${{ inputs.cloudflare_tunnel_listen }}
      run: $GITHUB_ACTION_PATH/scripts/autostart/Linux.sh
