name: Test setup-cloudflared
on:
  push:
    paths:
      - action.yml
      - scripts/**
      - shutdown/action.yml
      - .github/workflows/test.yaml
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cloudflared using setup-cloudflared
        uses: hack-the-6ix/cloudflared-tcp-action@main
        with:
          cloudflare_tunnel_service_token_id: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          cloudflare_tunnel_service_token_secret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}
          cloudflare_tunnel_hostname: "k8sapi-moose.hackthe6ix.com"
          
      - name: Test cloudflared installed by setup-cloudflared using Python HTTP server for 1 minute
        run: curl --proxy socks5://127.0.0.1:1234 https://10.20.0.3:16443 --insecure
        
      - name: Shutdown cloudflared using setup-cloudflared/shutdown
        if: always()
        uses: hack-the-6ix/cloudflared-tcp-action/shutdown@main
